vim.cmd("hi clear")
vim.g.colors_name = "pdc-dark"
vim.o.background = "dark"

local hi = function(group, opts)
  vim.api.nvim_set_hl(0, group, opts)
end

-- base
hi("Normal",       { fg = "#EDE7F4", bg = "NONE" })
hi("NormalFloat",  { fg = "#EDE7F4", bg = "#141414" })
hi("FloatBorder",  { fg = "#FF6B35", bg = "#141414" })
hi("CursorLine",   { bg = "#1a1410" })
hi("CursorLineNr", { fg = "#FF6B35", bold = true })
hi("LineNr",       { fg = "#666666" })
hi("Visual",       { bg = "#2a1810" })
hi("Search",       { fg = "#0d0806", bg = "#FF8C00" })
hi("IncSearch",    { fg = "#0d0806", bg = "#FF6B35" })
hi("Pmenu",        { fg = "#cccccc", bg = "#141414" })
hi("PmenuSel",     { fg = "#EDE7F4", bg = "#2a1810" })
hi("PmenuThumb",   { bg = "#FF6B35" })
hi("StatusLine",   { fg = "#EDE7F4", bg = "NONE" })
hi("StatusLineNC", { fg = "#666666", bg = "NONE" })
hi("TabLine",      { fg = "#999999", bg = "NONE" })
hi("TabLineSel",   { fg = "#FF6B35", bg = "NONE", bold = true })
hi("TabLineFill",  { bg = "NONE" })
hi("WinSeparator", { fg = "#2a1810" })
hi("SignColumn",   { bg = "NONE" })
hi("FoldColumn",   { fg = "#666666", bg = "NONE" })
hi("Folded",       { fg = "#999999", bg = "#141414" })
hi("MatchParen",   { fg = "#FF6B35", bold = true, underline = true })
hi("NonText",      { fg = "#333333" })
hi("SpecialKey",   { fg = "#333333" })
hi("Directory",    { fg = "#FF8C00" })
hi("Title",        { fg = "#FF6B35", bold = true })
hi("ErrorMsg",     { fg = "#FF6B35", bold = true })
hi("WarningMsg",   { fg = "#FFB347" })
hi("MoreMsg",      { fg = "#8B9A6B" })
hi("Question",     { fg = "#8B9A6B" })
hi("WildMenu",     { fg = "#0d0806", bg = "#FF6B35" })
hi("DiffAdd",      { bg = "#1a2a1a" })
hi("DiffChange",   { bg = "#1a1a2a" })
hi("DiffDelete",   { fg = "#FF6B35", bg = "#2a1410" })
hi("DiffText",     { bg = "#2a2a3a", bold = true })

-- syntax
hi("Comment",      { fg = "#666666", italic = true })
hi("Constant",     { fg = "#d19a66" })
hi("String",       { fg = "#98c379" })
hi("Character",    { fg = "#98c379" })
hi("Number",       { fg = "#FF8C00" })
hi("Boolean",      { fg = "#FF8C00" })
hi("Float",        { fg = "#FF8C00" })
hi("Identifier",   { fg = "#EDE7F4" })
hi("Function",     { fg = "#61afef" })
hi("Statement",    { fg = "#FF6B35" })
hi("Keyword",      { fg = "#FF6B35" })
hi("Operator",     { fg = "#cccccc" })
hi("PreProc",      { fg = "#FF8C00" })
hi("Type",         { fg = "#A0826D" })
hi("Special",      { fg = "#FF6B35" })
hi("Delimiter",    { fg = "#cccccc" })
hi("Todo",         { fg = "#0d0806", bg = "#FF6B35", bold = true })
hi("Error",        { fg = "#FF6B35", undercurl = true })

-- treesitter
hi("@variable",           { fg = "#EDE7F4" })
hi("@variable.builtin",   { fg = "#d19a66" })
hi("@constant",           { fg = "#d19a66" })
hi("@constant.builtin",   { fg = "#FF8C00" })
hi("@function",           { fg = "#61afef" })
hi("@function.builtin",   { fg = "#61afef" })
hi("@function.call",      { fg = "#61afef" })
hi("@method",             { fg = "#61afef" })
hi("@method.call",        { fg = "#61afef" })
hi("@keyword",            { fg = "#FF6B35" })
hi("@keyword.return",     { fg = "#FF6B35" })
hi("@keyword.function",   { fg = "#FF6B35" })
hi("@keyword.operator",   { fg = "#FF6B35" })
hi("@string",             { fg = "#98c379" })
hi("@string.escape",      { fg = "#FFB347" })
hi("@number",             { fg = "#FF8C00" })
hi("@boolean",            { fg = "#FF8C00" })
hi("@type",               { fg = "#A0826D" })
hi("@type.builtin",       { fg = "#A0826D" })
hi("@property",           { fg = "#cccccc" })
hi("@field",              { fg = "#cccccc" })
hi("@parameter",          { fg = "#C4A882" })
hi("@punctuation",        { fg = "#999999" })
hi("@punctuation.bracket", { fg = "#999999" })
hi("@punctuation.delimiter", { fg = "#999999" })
hi("@tag",                { fg = "#FF6B35" })
hi("@tag.attribute",      { fg = "#d19a66" })
hi("@tag.delimiter",      { fg = "#999999" })
hi("@comment",            { fg = "#666666", italic = true })
hi("@operator",           { fg = "#cccccc" })
hi("@constructor",        { fg = "#A0826D" })
hi("@namespace",          { fg = "#6D9B8B" })

-- diagnostics
hi("DiagnosticError",     { fg = "#FF6B35" })
hi("DiagnosticWarn",      { fg = "#FFB347" })
hi("DiagnosticInfo",      { fg = "#61afef" })
hi("DiagnosticHint",      { fg = "#6D9B8B" })
hi("DiagnosticUnderlineError", { undercurl = true, sp = "#FF6B35" })
hi("DiagnosticUnderlineWarn",  { undercurl = true, sp = "#FFB347" })
hi("DiagnosticUnderlineInfo",  { undercurl = true, sp = "#61afef" })
hi("DiagnosticUnderlineHint",  { undercurl = true, sp = "#6D9B8B" })

-- telescope
hi("TelescopeBorder",        { fg = "#FF6B35", bg = "NONE" })
hi("TelescopePromptBorder",  { fg = "#FF6B35", bg = "NONE" })
hi("TelescopePromptNormal",  { fg = "#EDE7F4", bg = "NONE" })
hi("TelescopePromptPrefix",  { fg = "#FF6B35" })
hi("TelescopeNormal",        { fg = "#cccccc", bg = "NONE" })
hi("TelescopeSelection",     { fg = "#EDE7F4", bg = "#2a1810" })
hi("TelescopeMatching",      { fg = "#FF8C00", bold = true })

-- neo-tree
hi("NeoTreeNormal",       { fg = "#cccccc", bg = "NONE" })
hi("NeoTreeNormalNC",      { fg = "#cccccc", bg = "NONE" })
hi("NeoTreeDirectoryIcon", { fg = "#FF8C00" })
hi("NeoTreeDirectoryName", { fg = "#FF8C00" })
hi("NeoTreeRootName",      { fg = "#FF6B35", bold = true })
hi("NeoTreeGitModified",   { fg = "#FFB347" })
hi("NeoTreeGitAdded",      { fg = "#8B9A6B" })
hi("NeoTreeGitDeleted",    { fg = "#FF6B35" })

-- which-key
hi("WhichKey",       { fg = "#FF6B35" })
hi("WhichKeyGroup",  { fg = "#FF8C00" })
hi("WhichKeyDesc",   { fg = "#cccccc" })
hi("WhichKeyBorder", { fg = "#2a1810" })

-- lualine handled via theme table in plugin config
