vim.cmd("hi clear")
vim.g.colors_name = "pdc-light"
vim.o.background = "light"

local hi = function(group, opts)
  vim.api.nvim_set_hl(0, group, opts)
end

-- base
hi("Normal",       { fg = "#1a1a2e", bg = "NONE" })
hi("NormalFloat",  { fg = "#1a1a2e", bg = "#ddd6ec" })
hi("FloatBorder",  { fg = "#7C3AED", bg = "#ddd6ec" })
hi("CursorLine",   { bg = "#ddd6ec" })
hi("CursorLineNr", { fg = "#7C3AED", bold = true })
hi("LineNr",       { fg = "#999aaa" })
hi("Visual",       { bg = "#d8d0f0" })
hi("Search",       { fg = "#ebe4f4", bg = "#7C3AED" })
hi("IncSearch",    { fg = "#ebe4f4", bg = "#6D28D9" })
hi("Pmenu",        { fg = "#333344", bg = "#ddd6ec" })
hi("PmenuSel",     { fg = "#1a1a2e", bg = "#d8d0f0" })
hi("PmenuThumb",   { bg = "#7C3AED" })
hi("StatusLine",   { fg = "#1a1a2e", bg = "NONE" })
hi("StatusLineNC", { fg = "#999aaa", bg = "NONE" })
hi("TabLine",      { fg = "#666677", bg = "NONE" })
hi("TabLineSel",   { fg = "#7C3AED", bg = "NONE", bold = true })
hi("TabLineFill",  { bg = "NONE" })
hi("WinSeparator", { fg = "#d8d0f0" })
hi("SignColumn",   { bg = "NONE" })
hi("FoldColumn",   { fg = "#999aaa", bg = "NONE" })
hi("Folded",       { fg = "#666677", bg = "#ddd6ec" })
hi("MatchParen",   { fg = "#7C3AED", bold = true, underline = true })
hi("NonText",      { fg = "#c0b8d0" })
hi("SpecialKey",   { fg = "#c0b8d0" })
hi("Directory",    { fg = "#6D28D9" })
hi("Title",        { fg = "#7C3AED", bold = true })
hi("ErrorMsg",     { fg = "#7C3AED", bold = true })
hi("WarningMsg",   { fg = "#7A1B2D" })
hi("MoreMsg",      { fg = "#5A7A4D" })
hi("Question",     { fg = "#5A7A4D" })
hi("WildMenu",     { fg = "#ebe4f4", bg = "#7C3AED" })
hi("DiffAdd",      { bg = "#d0e8d0" })
hi("DiffChange",   { bg = "#d8d0f0" })
hi("DiffDelete",   { fg = "#7C3AED", bg = "#e8d0e0" })
hi("DiffText",     { bg = "#c8c0e0", bold = true })

-- syntax
hi("Comment",      { fg = "#999aaa", italic = true })
hi("Constant",     { fg = "#7A1B2D" })
hi("String",       { fg = "#555566" })
hi("Character",    { fg = "#555566" })
hi("Number",       { fg = "#6D28D9" })
hi("Boolean",      { fg = "#6D28D9" })
hi("Float",        { fg = "#6D28D9" })
hi("Identifier",   { fg = "#1a1a2e" })
hi("Function",     { fg = "#1B5E3B" })
hi("Statement",    { fg = "#7C3AED" })
hi("Keyword",      { fg = "#7C3AED" })
hi("Operator",     { fg = "#333344" })
hi("PreProc",      { fg = "#6D28D9" })
hi("Type",         { fg = "#8B5CF6" })
hi("Special",      { fg = "#7C3AED" })
hi("Delimiter",    { fg = "#333344" })
hi("Todo",         { fg = "#ebe4f4", bg = "#7C3AED", bold = true })
hi("Error",        { fg = "#7C3AED", undercurl = true })

-- treesitter
hi("@variable",           { fg = "#1a1a2e" })
hi("@variable.builtin",   { fg = "#7A1B2D" })
hi("@constant",           { fg = "#7A1B2D" })
hi("@constant.builtin",   { fg = "#6D28D9" })
hi("@function",           { fg = "#1B5E3B" })
hi("@function.builtin",   { fg = "#1B5E3B" })
hi("@function.call",      { fg = "#1B5E3B" })
hi("@method",             { fg = "#1B5E3B" })
hi("@method.call",        { fg = "#1B5E3B" })
hi("@keyword",            { fg = "#7C3AED" })
hi("@keyword.return",     { fg = "#7C3AED" })
hi("@keyword.function",   { fg = "#7C3AED" })
hi("@keyword.operator",   { fg = "#7C3AED" })
hi("@string",             { fg = "#555566" })
hi("@string.escape",      { fg = "#7A1B2D" })
hi("@number",             { fg = "#6D28D9" })
hi("@boolean",            { fg = "#6D28D9" })
hi("@type",               { fg = "#8B5CF6" })
hi("@type.builtin",       { fg = "#8B5CF6" })
hi("@property",           { fg = "#333344" })
hi("@field",              { fg = "#333344" })
hi("@parameter",          { fg = "#A78BFA" })
hi("@punctuation",        { fg = "#666677" })
hi("@punctuation.bracket", { fg = "#666677" })
hi("@punctuation.delimiter", { fg = "#666677" })
hi("@tag",                { fg = "#7C3AED" })
hi("@tag.attribute",      { fg = "#7A1B2D" })
hi("@tag.delimiter",      { fg = "#666677" })
hi("@comment",            { fg = "#999aaa", italic = true })
hi("@operator",           { fg = "#333344" })
hi("@constructor",        { fg = "#8B5CF6" })
hi("@namespace",          { fg = "#4D7A6B" })

-- diagnostics
hi("DiagnosticError",     { fg = "#7C3AED" })
hi("DiagnosticWarn",      { fg = "#7A1B2D" })
hi("DiagnosticInfo",      { fg = "#1B5E3B" })
hi("DiagnosticHint",      { fg = "#4D7A6B" })
hi("DiagnosticUnderlineError", { undercurl = true, sp = "#7C3AED" })
hi("DiagnosticUnderlineWarn",  { undercurl = true, sp = "#7A1B2D" })
hi("DiagnosticUnderlineInfo",  { undercurl = true, sp = "#1B5E3B" })
hi("DiagnosticUnderlineHint",  { undercurl = true, sp = "#4D7A6B" })

-- telescope
hi("TelescopeBorder",        { fg = "#7C3AED", bg = "NONE" })
hi("TelescopePromptBorder",  { fg = "#7C3AED", bg = "NONE" })
hi("TelescopePromptNormal",  { fg = "#1a1a2e", bg = "NONE" })
hi("TelescopePromptPrefix",  { fg = "#7C3AED" })
hi("TelescopeNormal",        { fg = "#333344", bg = "NONE" })
hi("TelescopeSelection",     { fg = "#1a1a2e", bg = "#d8d0f0" })
hi("TelescopeMatching",      { fg = "#6D28D9", bold = true })

-- neo-tree
hi("NeoTreeNormal",       { fg = "#333344", bg = "NONE" })
hi("NeoTreeNormalNC",      { fg = "#333344", bg = "NONE" })
hi("NeoTreeDirectoryIcon", { fg = "#6D28D9" })
hi("NeoTreeDirectoryName", { fg = "#6D28D9" })
hi("NeoTreeRootName",      { fg = "#7C3AED", bold = true })
hi("NeoTreeGitModified",   { fg = "#7A1B2D" })
hi("NeoTreeGitAdded",      { fg = "#5A7A4D" })
hi("NeoTreeGitDeleted",    { fg = "#7C3AED" })

-- which-key
hi("WhichKey",       { fg = "#7C3AED" })
hi("WhichKeyGroup",  { fg = "#6D28D9" })
hi("WhichKeyDesc",   { fg = "#333344" })
hi("WhichKeyBorder", { fg = "#d8d0f0" })

-- lualine handled via theme table in plugin config
